# Generated by Django 4.0.6 on 2022-07-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='commissions_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
    ]
